# Thyroid_Data_Transformation

# <p style="padding:10px;background-color:#E9967A;margin:10;color:#0000FF;font-family:newtimeroman;font-size:100%;text-align:center;border-radius: 10px 10px;overflow:hidden;font-weight:30">Data Transformation</p>

In [1]:
# import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("thyroid.csv")

In [3]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,41.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,1.30,2.5,125.0,1.14,109.0,negative
1,23.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,4.10,2.0,102.0,0.98,107.0,negative
2,46.0,M,f,f,f,f,f,f,f,f,...,f,f,f,f,0.98,2.0,109.0,0.91,120.0,negative
3,70.0,F,t,f,f,f,f,f,f,f,...,f,f,f,f,0.16,1.9,175.0,0.98,107.0,negative
4,70.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,0.72,1.2,61.0,0.87,70.0,negative

In [4]:
df.shape

(2753, 22)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2753 entries, 0 to 2752
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        2753 non-null   float64
 1   sex                        2753 non-null   object
 2   on_thyroxine               2753 non-null   object
 3   query_on_thyroxine         2753 non-null   object
 4   on_antithyroid_medication  2753 non-null   object
 5   sick                       2753 non-null   object
 6   pregnant                   2753 non-null   object
 7   thyroid_surgery            2753 non-null   object
 8   I131_treatment             2753 non-null   object
 9   query_hypothyroid          2753 non-null   object
 10  query_hyperthyroid         2753 non-null   object
 11  lithium                    2753 non-null   object
 12  goitre                     2753 non-null   object
 13  tumor                      2753 non-null   object
 14  hypopituitary              2753 non-null   object
 15  psych                      2753 non-null   object
 16  TSH                        2753 non-null   float64
 17  T3                         2753 non-null   float64
 18  TT4                        2753 non-null   float64
 19  T4U                        2753 non-null   float64
 20  FTI                        2753 non-null   float64
 21  target                     2753 non-null   object
dtypes: float64(6), object(16)
memory usage: 473.3+ KB

In [6]:
df.columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH', 'T3', 'TT4', 'T4U',
       'FTI', 'target'],
      dtype='object')

In [7]:
df.isnull().sum()

age                          0
sex                          0
on_thyroxine                 0
query_on_thyroxine           0
on_antithyroid_medication    0
sick                         0
pregnant                     0
thyroid_surgery              0
I131_treatment               0
query_hypothyroid            0
query_hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
hypopituitary                0
psych                        0
TSH                          0
T3                           0
TT4                          0
T4U                          0
FTI                          0
target                       0
dtype: int64

In [8]:
X = df.drop(['target'], axis=1)

In [9]:
X

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI
0,41.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,f,1.30,2.5,125.0,1.14,109.0
1,23.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,f,4.10,2.0,102.0,0.98,107.0
2,46.0,M,f,f,f,f,f,f,f,f,...,f,f,f,f,f,0.98,2.0,109.0,0.91,120.0
3,70.0,F,t,f,f,f,f,f,f,f,...,f,f,f,f,f,0.16,1.9,175.0,0.98,107.0
4,70.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,f,0.72,1.2,61.0,0.87,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2748,70.0,M,f,f,f,f,f,f,f,f,...,f,f,f,f,f,2.70,2.0,155.0,1.05,148.0
2749,73.0,M,f,t,f,f,f,f,f,f,...,f,f,f,f,f,1.40,0.7,63.0,0.88,72.0
2750,75.0,M,f,f,f,f,f,f,f,f,...,f,f,f,f,f,1.40,2.0,147.0,0.80,183.0
2751,60.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,f,1.40,2.0,100.0,0.83,121.0
2752,81.0,F,f,f,f,f,f,f,f,f,...,f,f,f,f,f,1.20,1.5,114.0,0.99,115.0

In [10]:
y = df[['target']]

In [11]:
y

        target
0     negative
1     negative
2     negative
3     negative
4     negative
...        ...
2748  negative
2749  negative
2750  negative
2751  negative
2752  negative

[2753 rows x 1 columns]

In [12]:
df.describe().T

      count        mean        std    min    25%     50%     75%     max
age  2753.0   51.968398  20.508261  1.000  36.00   55.00   67.00  455.00
TSH  2753.0    4.390458  20.525596  0.005   0.57    1.40    2.40  478.00
T3   2753.0    2.020087   0.739685  0.050   1.70    2.00    2.30   10.60
TT4  2753.0  108.819978  34.517879  2.000  89.00  104.00  124.00  430.00
T4U  2753.0    0.996286   0.185422  0.310   0.89    0.98    1.07    2.12
FTI  2753.0  110.446749  31.386068  2.000  94.00  107.00  122.00  395.00

In [13]:
df.describe(include='object').T

                          count unique       top  freq
sex                        2753      2         F  1895
on_thyroxine               2753      2         f  2423
query_on_thyroxine         2753      2         f  2713
on_antithyroid_medication  2753      2         f  2720
sick                       2753      2         f  2643
pregnant                   2753      2         f  2712
thyroid_surgery            2753      2         f  2714
I131_treatment             2753      2         f  2705
query_hypothyroid          2753      2         f  2590
query_hyperthyroid         2753      2         f  2583
lithium                    2753      2         f  2739
goitre                     2753      2         f  2728
tumor                      2753      2         f  2682
hypopituitary              2753      2         f  2752
psych                      2753      2         f  2618
target                     2753      3  negative  2456

In [14]:
numerical_column = X.select_dtypes(exclude='object').columns
numerical_column

Index(['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI'], dtype='object')

In [15]:
categorical_column = X.select_dtypes(include='object').columns
categorical_column

Index(['sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych'],
      dtype='object')

# <p style="padding:10px;background-color:#E9967A;margin:10;color:#0000FF;font-family:newtimeroman;font-size:100%;text-align:center;border-radius: 10px 10px;overflow:hidden;font-weight:30">Creating Data Transformation Pipeline</p>

### Pipeline

        ~ Imputer
        ~ encoding
        ~ scaling

In [16]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [17]:
num_pipeline = Pipeline(
steps=[
    ("Imputer", SimpleImputer(strategy= "median")),
    ("Scaler", StandardScaler())
]
)


cat_pipeline = Pipeline(
steps=[
    ("Imputer", SimpleImputer(strategy= "most_frequent")),
    ("One_hot_encoder", OneHotEncoder(handle_unknown='ignore'))
]
)


preprocessor = ColumnTransformer([
    ('num_pipeline', num_pipeline, numerical_column),
    ('cat_pipeline', cat_pipeline, categorical_column)
])

In [18]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('Scaler', StandardScaler())]),
                                 Index(['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI'], dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('One_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych'],
      dtype='object'))])

In [19]:
# Train Test Slipt 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [20]:
preprocessor.fit_transform(X_train)

array([[-1.21324875, -0.10889089,  1.15004631, ...,  0.        ,
         1.        ,  0.        ],
       [-0.30976511,  0.95255496, -0.03540707, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.97413268, -0.21211407, -0.03540707, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.92658091, -0.15271205, -1.48429454, ...,  0.        ,
         1.        ,  0.        ],
       [-0.69017927, -0.20383674, -0.03540707, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.7839256 ,  0.1102149 , -0.82570933, ...,  0.        ,
         1.        ,  0.        ]])

In [21]:
X_train = pd.DataFrame(preprocessor.fit_transform(X_train), columns=preprocessor.get_feature_names_out())

In [22]:
X_train

,num_pipeline__age,num_pipeline__TSH,num_pipeline__T3,num_pipeline__TT4,num_pipeline__T4U,num_pipeline__FTI,cat_pipeline__sex_F,cat_pipeline__sex_M,cat_pipeline__on_thyroxine_f,cat_pipeline__on_thyroxine_t,...,cat_pipeline__lithium_f,cat_pipeline__lithium_t,cat_pipeline__goitre_f,cat_pipeline__goitre_t,cat_pipeline__tumor_f,cat_pipeline__tumor_t,cat_pipeline__hypopituitary_f,cat_pipeline__hypopituitary_t,cat_pipeline__psych_f,cat_pipeline__psych_t
0,-1.213249,-0.108891,1.150046,-0.672426,0.470232,-0.980244,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1,-0.309765,0.952555,-0.035407,-0.131749,-0.075272,-0.107455,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,0.974133,-0.212114,-0.035407,0.693496,-0.838978,1.482267,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.451063,-0.026118,0.886612,-0.700883,0.197480,-0.917902,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,1.497202,-0.089415,-0.957426,-0.245575,-0.729877,0.204255,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1922,-0.927938,-0.201402,1.281763,-0.217119,0.797535,-0.668534,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1923,-1.023042,-0.152712,0.359744,-0.074835,0.361131,-0.325652,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1924,0.926581,-0.152712,-1.484295,0.494299,-0.784428,1.170557,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1925,-0.690179,-0.203837,-0.035407,-0.729340,0.797535,-1.198441,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1926,0.783926,0.110215,-0.825709,-0.217119,-0.075272,-0.107455,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [23]:
preprocessor.get_feature_names_out()

array(['num_pipeline__age', 'num_pipeline__TSH', 'num_pipeline__T3',
       'num_pipeline__TT4', 'num_pipeline__T4U', 'num_pipeline__FTI',
       'cat_pipeline__sex_F', 'cat_pipeline__sex_M',
       'cat_pipeline__on_thyroxine_f', 'cat_pipeline__on_thyroxine_t',
       'cat_pipeline__query_on_thyroxine_f',
       'cat_pipeline__query_on_thyroxine_t',
       'cat_pipeline__on_antithyroid_medication_f',
       'cat_pipeline__on_antithyroid_medication_t',
       'cat_pipeline__sick_f', 'cat_pipeline__sick_t',
       'cat_pipeline__pregnant_f', 'cat_pipeline__pregnant_t',
       'cat_pipeline__thyroid_surgery_f',
       'cat_pipeline__thyroid_surgery_t',
       'cat_pipeline__I131_treatment_f', 'cat_pipeline__I131_treatment_t',
       'cat_pipeline__query_hypothyroid_f',
       'cat_pipeline__query_hypothyroid_t',
       'cat_pipeline__query_hyperthyroid_f',
       'cat_pipeline__query_hyperthyroid_t', 'cat_pipeline__lithium_f',
       'cat_pipeline__lithium_t', 'cat_pipeline__goitre_f',
       'cat_pipeline__goitre_t', 'cat_pipeline__tumor_f',
       'cat_pipeline__tumor_t', 'cat_pipeline__hypopituitary_f',
       'cat_pipeline__hypopituitary_t', 'cat_pipeline__psych_f',
       'cat_pipeline__psych_t'], dtype=object)

In [24]:
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [25]:
X_test

,num_pipeline__age,num_pipeline__TSH,num_pipeline__T3,num_pipeline__TT4,num_pipeline__T4U,num_pipeline__FTI,cat_pipeline__sex_F,cat_pipeline__sex_M,cat_pipeline__on_thyroxine_f,cat_pipeline__on_thyroxine_t,...,cat_pipeline__lithium_f,cat_pipeline__lithium_t,cat_pipeline__goitre_f,cat_pipeline__goitre_t,cat_pipeline__tumor_f,cat_pipeline__tumor_t,cat_pipeline__hypopituitary_f,cat_pipeline__hypopituitary_t,cat_pipeline__psych_f,cat_pipeline__psych_t
0,-0.690179,-0.172188,0.359744,-0.900080,-1.057180,-0.450336,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.831477,-0.215035,0.491461,0.778867,-0.402575,1.170557,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,1.734961,-0.104022,0.228027,-0.217119,0.033829,-0.294481,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,-0.072006,0.154036,-0.430558,0.551213,0.470232,0.235426,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.118201,-0.170241,-0.957426,-0.871623,0.688434,-1.260783,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,0.593719,-0.172188,-0.430558,-0.900080,-0.511676,-0.793218,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
822,-0.595076,-0.142974,1.018329,0.636583,1.452140,-0.200968,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
823,-1.260801,-0.201402,2.730651,1.404915,2.324947,0.017229,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
824,0.260856,-0.172188,0.096310,-0.444773,-0.511676,-0.200968,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
825,1.449650,-0.147843,-1.220860,-1.127734,-1.929987,-0.107455,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [26]:
import warnings
warnings.filterwarnings('ignore')

In [27]:
# importing the important libraries
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# create an instance of a GradientBoostingClassifier
GB_model = GradientBoostingClassifier()

# training the GradientBoostingClassifier model on the sampled train dataset
GB_model.fit(np.array(X_train), y_train)

# pedicting the labels on the test set
y_predicted_GB = GB_model.predict(np.array(X_test))

In [28]:
# import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# calculating the accuracy on train data
print('Accuracy Score on train data: ', metrics.accuracy_score(y_true = y_train,\
                                                               y_pred = GB_model.predict(X_train)))

# calculating the accuracy on test data
print('Accuracy Score on test data: ', metrics.accuracy_score(y_true = y_test, y_pred = y_predicted_GB))

Accuracy Score on train data:  1.0
Accuracy Score on test data:  0.9854721549636803

In [29]:
print("****** GradientBoostingClassifier Model Prediction on Test Data ******")
print("********************************************************************\n")
print("--------- Confusion Matrix ---------\n\n", confusion_matrix(y_test, y_predicted_GB))
print("\n------------------------------------")
print("Acurracy Score:", accuracy_score(y_test, y_predicted_GB))
print("------------------------------------")
print("\n------ Classification Report -------\n\n", classification_report(y_test, y_predicted_GB))
print("--------------------------------------------------------")

****** GradientBoostingClassifier Model Prediction on Test Data ******
********************************************************************

--------- Confusion Matrix ---------

 [[ 16   1   5]
 [  0  71   1]
 [  5   0 727]]

------------------------------------
Acurracy Score: 0.9854721549636803
------------------------------------

------ Classification Report -------

               precision    recall  f1-score   support

hyperthyroid       0.76      0.73      0.74        22
 hypothyroid       0.99      0.99      0.99        72
    negative       0.99      0.99      0.99       732

    accuracy                           0.99       826
   macro avg       0.91      0.90      0.91       826
weighted avg       0.99      0.99      0.99       826

--------------------------------------------------------